# Generated by Django 4.0.1 on 2022-02-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monte_carlo', '0002_assumptions_remove_monte_carlo_monte_carlo_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_balance', models.FloatField(default=10000)),
                ('position_size', models.FloatField(default=1.5)),
            ],
        ),
        migrations.DeleteModel(
            name='Monte_carlo',
        ),
    ]
