# Generated by Django 4.0.1 on 2022-01-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oscarrr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oscarrr_text', models.CharField(max_length=500, verbose_name='oscarrr')),
            ],
        ),
    ]
