# Generated by Django 4.0.1 on 2022-02-02 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oscarrr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oscarrr',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oscarrr',
            name='symbol',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
